// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bijcexwmtiunnlxvibvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpamNleHdtdGl1bm5seHZpYnZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzQ5NTksImV4cCI6MjA2MTE1MDk1OX0.s2cihfXaoTI2PTlr4ba-HtN4g4IdKQ48RwTVNX0KfzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);